apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
    
        hosts {
            $INGRESS_NGINX gitlab.gitlab.local
            $INGRESS_NGINX harbor.local
        }

        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health {\n       lameduck 5s\n    }\n    ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n       pods insecure\n       fallthrough in-addr.arpa ip6.arpa\n       ttl 30\n    }\n    prometheus :9153\n\n    forward . /etc/resolv.conf {\n       max_concurrent 1000\n    }\n    cache 30\n    loop\n    reload\n    loadbalance\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-02-02T07:17:10Z","name":"coredns","namespace":"kube-system","resourceVersion":"49216","uid":"ce067751-f54e-40e4-bf6c-3eb68a63f131"}}
  creationTimestamp: "2025-02-02T07:17:10Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "49810"
  uid: ce067751-f54e-40e4-bf6c-3eb68a63f131
