global:
  edition: ce  # ce (Community Edition) 또는 ee (Enterprise Edition) 선택
  hosts:
    domain: gitlab.local  # 사용할 도메인 입력
    externalIP: ""  # 클러스터의 외부 IP 주소
  ingress:
    configureCertmanager: false  # Cert-Manager 사용 여부
    tls:
      enabled: true
      secretName: gitlab-tls  # TLS 인증서 시크릿 이름

externalUrl: https://gitlab.gitlab.local

gitlab-runner:
  install: true
  rbac:
    create: true
  runners:
    locked: false
    secret: "nonempty"
    config: |
      [[runners]]
        name = "my-docker-runner"
        url = "https://gitlab.gitlab.local"
        
        executor = "docker"

        [runners.docker]
          image = "docker:20.10.16-dind"
          hostname = "my-runner-job"

          privileged = true
          tls_verify = false
          # extra_hosts = ["도메인:IP"] 형식
          extra_hosts = ["gitlab.gitlab.local:10.96.209.217"]
  podAnnotations:
    gitlab.com/prometheus_scrape: "true"
    gitlab.com/prometheus_port: 9252
  podSecurityContext:
    seccompProfile:
      type: "RuntimeDefault"

certmanager:
  install: false  # Cert-Manager가 이미 설치되어 있다면 false

gitlab:
  webservice:
    replicas: 1  # 웹 서비스 복제본 수
  gitlabInitialRootPassword: "root"

postgresql:
  install: true
  postgresqlPassword: "root"  # PostgreSQL 비밀번호 설정

redis:
  install: true
  password: "root"  # Redis 비밀번호 설정
