# harbor-gitlab-values.yaml
expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secretName: harbor-tls
  ingress:
    hosts:
      core: harbor.local
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "0"

harborAdminPassword: "Harbor12345" # 보안상 강력한 비밀번호 사용 권장

externalURL: https://harbor.local
