replicaCount: 2

image:
  repository: my-registry/gateway
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: gateway.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

rollout:
  enabled: true
  steps:
    - setWeight: 20
    - pause: { duration: 30s }
    - setWeight: 50
    - pause: { duration: 30s }
